version: '3.8'

services:
  # Servicio de Base de Datos MySQL
  mysqldb:
    image: mysql:8.0
    container_name: aseguradora_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aseguradora_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker-data:/var/lib/mysql  # Persistencia de datos
      - ./init-scripts:/docker-entrypoint-initdb.d # Script inicial