version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aseguradora_db
    ports:
      - "3307:3306"
    volumes:
      # ESTA es la línea mágica que te falta o está mal:
      # Conecta tu carpeta local con la carpeta de inicio de la base de datos
      - ./init-scripts:/docker-entrypoint-initdb.d
      
      # Este es el volumen para guardar los datos (persistencia)
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: